{% set name = "aws-checksums" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0f897686f1963253c5069a0e495b85c31635ba146cd3ac38cc2ea31eaf54694d

build:
  number: 4
  run_exports:
    - {{ pin_subpackage("aws-checksums", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common

test:
  commands:
    - test -f $PREFIX/lib/libaws-checksums${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/checksums/exports.h  # [unix]

about:
  home: https://github.com/awslabs/aws-checksums
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cross-Platform HW accelerated CRC32c and CRC32 with fallback to efficient SW implementations. C interface with language bindings for each of our SDKs.

extra:
  recipe-maintainers:
    - xhochy
